[package]
authors = ["Ballerina"]
distribution = "2201.12.0"
keywords = ["Vendor/Google", "Area/AI & Machine Learning", "Type/Embedding Provider", "Type/Model Provider", "Type/Connector", "Name/Google Gemini Model/Embedding Provider"]
license = ["Apache-2.0"]
icon="icon.png"
name = "ai.google.gemini"
org = "ballerinax"
repository = "https://github.com/ballerina-platform/module-ballerinax-ai.google.gemini"
version = "0.9.0"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.lib"
artifactId = "ai.google.gemini-native"
version = "0.9.0"
path = "../native/build/libs/ai.google.gemini-native-0.9.0-SNAPSHOT.jar"
