// Copyright (c) 2026 WSO2 LLC (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/ai;
import ballerina/ai.observe;
import ballerina/http;
import ballerina/jballerina.java;

const DEFAULT_GEMINI_SERVICE_URL = "https://generativelanguage.googleapis.com/v1beta";
# Upper bound on tokens generated per request.
#
# Set to the Gemini 2.5+ maximum output limit (65,536) rather than a small value,
# because thinking tokens are billed against `maxOutputTokens` on every model this
# connector targets. Gemini 2.5 Flash alone may spend up to 24,576 tokens on internal
# reasoning, so a low cap can be consumed entirely by thinking, returning a candidate
# with `finishReason` "MAX_TOKENS" and no text part. This is a ceiling, not a target —
# billing follows the tokens actually produced.
const DEFAULT_MAX_TOKEN_COUNT = 65536;

# Header used to authenticate Gemini API requests with an API key.
const API_KEY_HEADER = "x-goog-api-key";

# Roles understood by the Gemini `contents` array.
const GEMINI_ROLE_USER = "user";
const GEMINI_ROLE_MODEL = "model";

# Schema combinators that are normalised to `anyOf` before sending.
#
# Tool and response schemas are sent through Gemini's standard-JSON-Schema fields
# (`parametersJsonSchema` / `responseJsonSchema`), which accept `$ref`, `$defs`,
# `additionalProperties`, `title` and `prefixItems` directly — so no keyword stripping
# is required. `anyOf` is explicitly documented as the supported union combinator,
# while `oneOf` and `allOf` are not listed, so they are rewritten to `anyOf`.
#
# For a union type this is semantically equivalent in practice: the generated schemas
# describe mutually exclusive alternatives, which `anyOf` also satisfies.
# Reference: https://blog.google/innovation-and-ai/technology/developers-tools/gemini-api-structured-outputs/
final string[] & readonly NORMALIZED_SCHEMA_COMBINATORS = ["oneOf", "allOf"];

# ModelProvider is a client class that provides an interface for interacting with Gemini Large Language Models.
public isolated distinct client class ModelProvider {
    *ai:ModelProvider;
    // A single raw HTTP client posts JSON to the Gemini `:generateContent` API.
    private final http:Client httpClient;
    // Read by the native `Generator` shim via field lookup; see `Generator.java`.
    private final string apiKey;
    private final GEMINI_MODEL_NAMES modelType;
    private final decimal? temperature;
    private final int maxTokens;

    # Initializes the Gemini model with the given connection configuration and model configuration.
    #
    # + apiKey - The Gemini API key
    # + modelType - The Gemini model name
    # + serviceUrl - The base URL of Gemini API endpoint
    # + maxTokens - The upper limit for the number of tokens in the response generated by the model
    # + temperature - The temperature for controlling randomness in the model's output. Left
    #                 unset when `()`, so the model's own default applies. Google strongly
    #                 recommends leaving this unset for Gemini 3 models: values below the
    #                 default of `1.0` may cause looping or degraded performance on complex
    #                 reasoning tasks
    # + connectionConfig - Additional HTTP connection configuration
    # + return - `()` on successful initialization; otherwise, returns an `ai:Error`
    public isolated function init(@display {label: "API Key"} string apiKey,
            @display {label: "Model Type"} GEMINI_MODEL_NAMES modelType,
            @display {label: "Service URL"} string serviceUrl = DEFAULT_GEMINI_SERVICE_URL,
            @display {label: "Maximum Tokens"} int maxTokens = DEFAULT_MAX_TOKEN_COUNT,
            @display {label: "Temperature"} decimal? temperature = (),
            @display {label: "Connection Configuration"} *ConnectionConfig connectionConfig) returns ai:Error? {
        // `ConnectionConfig` is a field-compatible subset of `http:ClientConfiguration`
        // (it omits `auth` because Gemini authenticates via the `x-goog-api-key`
        // header, set per request), so it can be spread directly.
        http:Client|error httpClient = new (serviceUrl, {...connectionConfig});
        if httpClient is error {
            return error ai:Error("Failed to initialize the Gemini client", httpClient);
        }
        self.httpClient = httpClient;
        self.apiKey = apiKey;
        self.modelType = modelType;
        self.temperature = temperature;
        self.maxTokens = maxTokens;
    }

    # Sends a chat request to the Gemini model with the given messages and tools.
    #
    # + messages - List of chat messages or a single user message
    # + tools - Tool definitions to be used for the tool call
    # + stop - Stop sequence to stop the completion
    # + return - Function to be called, chat response or an error in-case of failures
    isolated remote function chat(ai:ChatMessage[]|ai:ChatUserMessage messages, ai:ChatCompletionFunctions[] tools = [],
            string? stop = ()) returns ai:ChatAssistantMessage|ai:Error {
        observe:ChatSpan span = observe:createChatSpan(self.modelType);
        span.addProvider("gemini");
        if stop is string {
            span.addStopSequence(stop);
        }
        decimal? spanTemperature = self.temperature;
        if spanTemperature is decimal {
            span.addTemperature(spanTemperature);
        }
        json|ai:Error inputMessage = convertMessageToJson(messages);
        if inputMessage is json {
            span.addInputMessages(inputMessage);
        }

        GenerateContentRequest|ai:Error request = self.buildGenerateContentRequest(messages, tools, stop);
        if request is ai:Error {
            span.close(request);
            return request;
        }
        if tools.length() > 0 {
            span.addTools(tools);
        }

        map<string|string[]> headers = {[API_KEY_HEADER]: self.apiKey};
        string path = string `/models/${self.modelType}:generateContent`;
        GenerateContentResponse|error response = self.httpClient->post(path, request, headers);
        if response is error {
            ai:Error err = mapHttpError(response);
            span.close(err);
            return err;
        }

        Candidate[]? candidates = response.candidates;
        if candidates is () || candidates.length() == 0 {
            ai:Error err = error ai:LlmInvalidResponseError(buildEmptyCandidatesMessage(response));
            span.close(err);
            return err;
        }
        Candidate candidate = candidates[0];

        recordResponseTelemetry(span, response);
        string? finishReason = candidate.finishReason;
        if finishReason is string {
            span.addFinishReason(finishReason);
        }

        ai:ChatAssistantMessage message = convertCandidateToAssistantMessage(candidate);
        // A candidate that yielded neither text nor a function call is not a valid
        // assistant turn. Returning it as-is produces a message with `content` and
        // `toolCalls` both `()`, which fails opaquely further down an agent loop.
        if message.content is () && message.toolCalls is () {
            ai:Error err = error ai:LlmInvalidResponseError(
                    buildUnusableCandidateMessage(candidate, response));
            span.close(err);
            return err;
        }
        span.addOutputMessages(stripThoughtSignatures(message));
        span.addOutputType(observe:TEXT);
        span.close();
        return message;
    }

    # Sends a chat request to the model and generates a value that belongs to the type
    # corresponding to the type descriptor argument.
    #
    # + prompt - The prompt to use in the chat messages
    # + td - Type descriptor specifying the expected return type format
    # + return - Generates a value that belongs to the type, or an error if generation fails
    isolated remote function generate(ai:Prompt prompt, @display {label: "Expected type"} typedesc<anydata> td = <>) returns td|ai:Error = @java:Method {
        'class: "io.ballerina.lib.ai.google.gemini.Generator"
    } external;

    # Builds a Gemini `generateContent` request from the normalized `ai` chat messages.
    # System messages are collapsed into a single `systemInstruction`; user, assistant
    # (including tool calls) and function-result messages become `contents` entries.
    #
    # + messages - The chat messages, or a single user message
    # + tools - Tool definitions to expose as function declarations
    # + stop - Optional stop sequence
    # + return - The assembled request, or an `ai:Error` if a message cannot be converted
    private isolated function buildGenerateContentRequest(ai:ChatMessage[]|ai:ChatUserMessage messages,
            ai:ChatCompletionFunctions[] tools, string? stop) returns GenerateContentRequest|ai:Error {
        Content[] contents = [];
        Content? systemInstruction = ();

        if messages is ai:ChatUserMessage {
            contents.push({role: GEMINI_ROLE_USER, parts: [{text: check getChatMessageStringContent(messages.content)}]});
        } else {
            int index = 0;
            while index < messages.length() {
                ai:ChatMessage message = messages[index];
                if message is ai:ChatSystemMessage {
                    string systemText = check getChatMessageStringContent(message.content);
                    if systemInstruction is Content {
                        // Gemini concatenates the parts of `systemInstruction` with no
                        // separator, so successive instructions would run together as
                        // "...be concise.You are a helpful assistant." Prefix a newline.
                        systemInstruction.parts.push({text: "\n" + systemText});
                    } else {
                        systemInstruction = {parts: [{text: systemText}]};
                    }
                    index += 1;
                } else if message is ai:ChatUserMessage {
                    contents.push({role: GEMINI_ROLE_USER, parts: [{text: check getChatMessageStringContent(message.content)}]});
                    index += 1;
                } else if message is ai:ChatAssistantMessage {
                    // Consumes the tool results that follow it, and any continuation of the
                    // same parallel batch, so the whole exchange lands in the two content
                    // entries Gemini expects rather than one pair per call.
                    index = appendAssistantTurn(messages, index, contents);
                } else {
                    contents.push(buildFunctionResponseContent(<ai:ChatFunctionMessage>message));
                    index += 1;
                }
            }
        }

        GenerationConfig generationConfig = {maxOutputTokens: self.maxTokens};
        decimal? temperature = self.temperature;
        if temperature is decimal {
            generationConfig.temperature = temperature;
        }
        if stop is string {
            generationConfig.stopSequences = [stop];
        }

        GenerateContentRequest request = {contents, generationConfig};
        if systemInstruction is Content {
            request.systemInstruction = systemInstruction;
        }
        if tools.length() > 0 {
            request.tools = [{functionDeclarations: convertTools(tools)}];
        }
        return request;
    }
}

# Maps a Gemini response candidate onto a normalized `ai:ChatAssistantMessage`.
# Text parts are concatenated into `content`; `functionCall` parts become `toolCalls`.
#
# + candidate - The first candidate from a `generateContent` response
# + return - The normalized assistant message
isolated function convertCandidateToAssistantMessage(Candidate candidate) returns ai:ChatAssistantMessage {
    ai:ChatAssistantMessage assistantMessage = {role: ai:ASSISTANT};
    Content? content = candidate.content;
    if content is () {
        return assistantMessage;
    }

    string textContent = "";
    ai:FunctionCall[] toolCalls = [];
    foreach Part part in content.parts {
        string? text = part.text;
        if text is string {
            textContent += text;
        }
        FunctionCall? functionCall = part.functionCall;
        if functionCall is FunctionCall {
            ai:FunctionCall call = {name: functionCall.name, arguments: functionCall.args ?: {}};
            // Gemini 3 rejects a replay of this call that has lost the signature it arrived
            // with, and `ai:FunctionCall` has no field to hold one, so it rides on the id.
            // On parallel calls Gemini signs the first part — the signature covers the whole
            // turn — so the rest are marked as continuations of it, and a signature on one of
            // them is carried too rather than discarded by the marking.
            string? id = packToolCallId(functionCall.id, part.thoughtSignature, toolCalls.length() > 0);
            if id is string {
                call.id = id;
            }
            toolCalls.push(call);
        }
    }

    if textContent.length() > 0 {
        assistantMessage.content = textContent;
    }
    if toolCalls.length() > 0 {
        assistantMessage.toolCalls = toolCalls;
    }
    return assistantMessage;
}

# Rebuilds one model turn, starting from the assistant message at `startIndex`, and
# appends it — with the tool results that answer it — to `contents`.
#
# Gemini returns every parallel tool call as one model turn, signing only the first part;
# the signature covers the turn as a whole. The agent runtime replays that turn as one
# assistant message per call, which strands the unsigned calls in content entries of their
# own, and Gemini rejects those: "Function call is missing a thought_signature in
# functionCall parts". Folding the continuations back in restores the exact shape Gemini
# emitted, which is also what the official SDKs send.
#
# The tool results are gathered into a single `user` entry for the same reason — that is
# how Gemini pairs a batch of calls with its results.
#
# + messages - The full message list
# + startIndex - Index of the assistant message opening the turn
# + contents - The contents being assembled; the model turn and its results are appended
# + return - The index of the first message not consumed
isolated function appendAssistantTurn(ai:ChatMessage[] messages, int startIndex, Content[] contents) returns int {
    ai:ChatMessage message = messages[startIndex];
    Part[] parts = message is ai:ChatAssistantMessage ? assistantParts(message) : [];
    Part[] resultParts = [];
    int next = startIndex + 1;
    while next < messages.length() {
        ai:ChatMessage following = messages[next];
        if following is ai:ChatFunctionMessage {
            resultParts.push(functionResponsePart(following));
        } else if following is ai:ChatAssistantMessage && continuesToolCallBatch(following) {
            parts.push(...assistantParts(following));
        } else {
            break;
        }
        next += 1;
    }
    // An assistant message carrying neither content nor tool calls yields no parts; it is
    // omitted rather than sent as an empty (or empty-text) part, which Gemini rejects.
    if parts.length() > 0 {
        contents.push({role: GEMINI_ROLE_MODEL, parts});
    }
    if resultParts.length() > 0 {
        contents.push({role: GEMINI_ROLE_USER, parts: resultParts});
    }
    return next;
}

# Builds the `model`-role parts for an assistant message: its text, then one `functionCall`
# part per tool call, each carrying back the thought signature packed onto its id.
#
# + message - The assistant message to convert
# + return - The parts, empty when the message carries neither content nor tool calls
isolated function assistantParts(ai:ChatAssistantMessage message) returns Part[] {
    Part[] parts = [];
    string? content = message?.content;
    if content is string && content.length() > 0 {
        parts.push({text: content});
    }
    ai:FunctionCall[]? toolCalls = message.toolCalls;
    if toolCalls is ai:FunctionCall[] {
        foreach ai:FunctionCall functionCall in toolCalls {
            FunctionCall call = {name: functionCall.name, args: functionCall.arguments};
            // The signature was packed onto the id on the way out; it belongs on the part,
            // not inside `functionCall`, and only Gemini's own id may go back on the wire.
            ToolCallId toolCallId = unpackToolCallId(functionCall.id);
            string? id = toolCallId.id;
            if id is string {
                call.id = id;
            }
            Part part = {functionCall: call};
            string? signature = toolCallId.signature;
            if signature is string {
                part.thoughtSignature = signature;
            }
            parts.push(part);
        }
    }
    return parts;
}

# Builds a `functionResponse` content from a tool-result message.
#
# Sent with the `user` role. Gemini's `Content.role` is documented as accepting only
# `user` and `model`, so a tool result cannot use a `function` role and is attributed
# to `user` instead.
#
# The result string is parsed as JSON. An object is passed through as-is; any other
# JSON value (array, number, string, boolean) is wrapped as `{"result": <value>}` so
# that structure is preserved. Text that is not valid JSON is wrapped as a string.
#
# + message - The function/tool result message
# + return - The corresponding Gemini content
isolated function buildFunctionResponseContent(ai:ChatFunctionMessage message) returns Content =>
    {role: GEMINI_ROLE_USER, parts: [functionResponsePart(message)]};

# Builds the `functionResponse` part for a tool-result message. See
# `buildFunctionResponseContent` for how the result payload is shaped.
#
# + message - The function/tool result message
# + return - The corresponding part
isolated function functionResponsePart(ai:ChatFunctionMessage message) returns Part {
    map<json> response = {};
    string? content = message?.content;
    if content is string {
        json|error parsed = content.fromJsonString();
        if parsed is map<json> {
            response = parsed;
        } else if parsed is json {
            // Arrays and scalars are valid tool results. Wrapping the *parsed* value
            // keeps them structured; wrapping the raw string would hand the model
            // `{"result":"[1,2,3]"}` instead of `{"result":[1,2,3]}`.
            response = {result: parsed};
        } else {
            response = {result: content};
        }
    }
    FunctionResponse functionResponse = {name: message.name, response};
    // The agent copies the tool-call id onto the result message, so this id may carry a
    // packed signature or batch marker. Only Gemini's own id may be echoed back.
    string? id = unpackToolCallId(message?.id).id;
    if id is string {
        functionResponse.id = id;
    }
    return {functionResponse};
}

# Converts `ai` tool definitions into Gemini function declarations, sending the
# parameter schema through `parametersJsonSchema` so standard JSON Schema — including
# `$ref`/`$defs` for nested records — is accepted as-is.
#
# + tools - The tool definitions
# + return - The function declarations for a single Gemini `Tool`
isolated function convertTools(ai:ChatCompletionFunctions[] tools) returns FunctionDeclaration[] {
    FunctionDeclaration[] declarations = [];
    foreach ai:ChatCompletionFunctions tool in tools {
        FunctionDeclaration declaration = {name: tool.name, description: tool.description};
        map<json>? params = tool?.parameters;
        if params is map<json> {
            declaration.parametersJsonSchema = normalizeJsonObjectSchema(params);
        }
        declarations.push(declaration);
    }
    return declarations;
}

# Recursively removes JSON-schema keywords unsupported by Gemini's function-calling
# schema (see `UNSUPPORTED_SCHEMA_KEYS`) from a schema value.
#
# + schema - The schema (object, array, or scalar) to sanitize
# + return - The sanitized schema
isolated function normalizeJsonSchema(json schema) returns json {
    if schema is map<json> {
        return normalizeJsonObjectSchema(schema);
    }
    if schema is json[] {
        return schema.'map(item => normalizeJsonSchema(item));
    }
    return schema;
}

# Normalises an object schema for Gemini's standard-JSON-Schema fields.
#
# Only `oneOf` / `allOf` are rewritten (to `anyOf`); every other keyword is passed
# through untouched, because `parametersJsonSchema` and `responseJsonSchema` accept
# standard JSON Schema. Returning `map<json>` rather than `json` keeps the object type
# so call sites need no fallback.
#
# + schema - The object schema to normalise
# + return - The normalised object schema
isolated function normalizeJsonObjectSchema(map<json> schema) returns map<json> {
    map<json> result = {};
    foreach [string, json] [key, value] in schema.entries() {
        string targetKey = NORMALIZED_SCHEMA_COMBINATORS.indexOf(key) is int ? "anyOf" : key;
        result[targetKey] = normalizeJsonSchema(value);
    }
    return result;
}

isolated function getChatMessageStringContent(ai:Prompt|string prompt) returns string|ai:Error {
    if prompt is string {
        return prompt;
    }
    string[] & readonly strings = prompt.strings;
    anydata[] insertions = prompt.insertions;
    string promptStr = strings[0];
    foreach int i in 0 ..< insertions.length() {
        string str = strings[i + 1];
        anydata insertion = insertions[i];

        if insertion is ai:TextDocument|ai:TextChunk {
            promptStr += insertion.content + " " + str;
            continue;
        }

        if insertion is ai:TextDocument[] {
            foreach ai:TextDocument doc in insertion {
                promptStr += doc.content + " ";
            }
            promptStr += str;
            continue;
        }

        if insertion is ai:TextChunk[] {
            foreach ai:TextChunk doc in insertion {
                promptStr += doc.content + " ";
            }
            promptStr += str;
            continue;
        }

        if insertion is ai:Document {
            return error ai:Error("Only Text Documents are currently supported.");
        }

        promptStr += insertion.toString() + str;
    }
    return promptStr.trim();
}

isolated function convertMessageToJson(ai:ChatMessage[]|ai:ChatMessage messages) returns json|ai:Error {
    if messages is ai:ChatMessage[] {
        // An explicit loop, not `.'map`: `lang.array:map` has no error in its inferred
        // member type, so a `check` failing inside the lambda panics instead of
        // returning the `ai:Error` this function declares.
        json[] converted = [];
        foreach ai:ChatMessage message in messages {
            converted.push(check convertMessageToJson(message));
        }
        return converted;
    }
    return messages !is ai:ChatUserMessage|ai:ChatSystemMessage ? messages :
        {role: messages.role, content: check getChatMessageStringContent(messages.content), name: messages.name};
}
